FROM python:3.9-slim

WORKDIR /app

COPY module.py .
COPY .env .
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 80

ENV TEXT_INPUT=TEXT_INPUT
ENV SELECT=SELECT

CMD ["python", "module.py"]